image: dlp

stages:
- cours
- tme


ILP1:
  stage: cours
  script: >
    /home/dlp/run.sh -id ILP1 -name ILP1
    com.paracamplus.ilp1.interpreter.test.InterpreterTest
    com.paracamplus.ilp1.compiler.test.CompilerTest
  artifacts:
    reports:
      junit: report.xml
      
TME1:
  stage: tme
  script: >
    /home/dlp/run.sh -id TME1 -name TME1
    com.paracamplus.ilp1.ilp1tme1.test.Tme1InterpreterTest
    com.paracamplus.ilp1.ilp1tme1.test.Tme1CompilerTest
    com.paracamplus.ilp1.ilp1tme1.sequence.ASTsequenceTest
    com.paracamplus.ilp1.ilp1tme1.sequence.InterpreterTest
  artifacts:
    reports:
      junit: report.xml

TME2:
  stage: tme
  script: >
    /home/dlp/run.sh -id TME2 -name TME2
    com.paracamplus.ilp1.ilp1tme2.ex2.InterpreterTest
  artifacts:
    reports:
      junit: report.xml